# Generated by Django 4.2.4 on 2023-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlisting',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='auction_category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys & Games', 'Toys & Games'), ('Electronics', 'Electronics'), ('Mobile Phones', 'Mobile Phones'), ('Home', 'Home'), ('Sports & Outdoor', 'Sports & Outdoor'), ('Vehicles', 'Vehicles'), ('Beauty', 'Beauty'), ('Furniture', 'Furniture'), ('Jewelry & Watches', 'Jewelry & Watches')], max_length=100),
        ),
    ]
