# Generated by Django 4.2.4 on 2023-08-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='auction_category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys & Games', 'Toys & Games'), ('Electronics', 'Electronics'), ('Mobile Phones', 'Mobile Phones'), ('Home', 'Home'), ('Sports & Outdoor', 'Sports & Outdoor'), ('Vehicles', 'Vehicles'), ('Beauty', 'Beauty'), ('Furniture', 'Furniture'), ('Jewelry & Watches', 'Jewelry & Watches'), ('Collectibles & Art', 'Collectibles & Art'), ('Music & Musical Instruments', 'Music & Musical Instruments')], max_length=100),
        ),
    ]
