# Generated by Django 4.2.4 on 2023-09-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_wishlist_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='wishlist',
            new_name='favourite',
        ),
    ]
