# Generated by Django 4.2.4 on 2023-09-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bids_options_bids_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='time_left',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
